/* Generated By:JavaCC: Do not edit this line. VerificadorSintaxeConstants.java */
package Compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VerificadorSintaxeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NULL = 11;
  /** RegularExpression Id. */
  int IMPORT = 12;
  /** RegularExpression Id. */
  int PACKAGE = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int STATIC = 22;
  /** RegularExpression Id. */
  int PUBLIC = 23;
  /** RegularExpression Id. */
  int PROTECTED = 24;
  /** RegularExpression Id. */
  int PRIVATE = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int INT = 27;
  /** RegularExpression Id. */
  int BOOLEAN = 28;
  /** RegularExpression Id. */
  int CHAR = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int VOID = 32;
  /** RegularExpression Id. */
  int AC = 33;
  /** RegularExpression Id. */
  int FC = 34;
  /** RegularExpression Id. */
  int AP = 35;
  /** RegularExpression Id. */
  int FP = 36;
  /** RegularExpression Id. */
  int AB = 37;
  /** RegularExpression Id. */
  int FB = 38;
  /** RegularExpression Id. */
  int VIRGULA = 39;
  /** RegularExpression Id. */
  int PONTO = 40;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 41;
  /** RegularExpression Id. */
  int PONTO_ASTERISCO = 42;
  /** RegularExpression Id. */
  int SOMA = 43;
  /** RegularExpression Id. */
  int SUBTRACAO = 44;
  /** RegularExpression Id. */
  int MUTIPLICACAO = 45;
  /** RegularExpression Id. */
  int DIVISAO = 46;
  /** RegularExpression Id. */
  int MODULO = 47;
  /** RegularExpression Id. */
  int SOMA_PLUS = 48;
  /** RegularExpression Id. */
  int SUBTRACAO_PLUS = 49;
  /** RegularExpression Id. */
  int MULTIPLICACAO_PLUS = 50;
  /** RegularExpression Id. */
  int DIVISAO_PLUS = 51;
  /** RegularExpression Id. */
  int MODULO_PLUS = 52;
  /** RegularExpression Id. */
  int ATRIBUICAO = 53;
  /** RegularExpression Id. */
  int INCREMENTO = 54;
  /** RegularExpression Id. */
  int DECREMENTO = 55;
  /** RegularExpression Id. */
  int IGUALDADE = 56;
  /** RegularExpression Id. */
  int DIFERENCA = 57;
  /** RegularExpression Id. */
  int MENOR = 58;
  /** RegularExpression Id. */
  int MAIOR = 59;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 60;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 61;
  /** RegularExpression Id. */
  int AND = 62;
  /** RegularExpression Id. */
  int OR = 63;
  /** RegularExpression Id. */
  int NEGACAO = 64;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 65;
  /** RegularExpression Id. */
  int LETRA = 66;
  /** RegularExpression Id. */
  int DIGITO = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 69;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 70;
  /** RegularExpression Id. */
  int EXPONENT = 71;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 72;
  /** RegularExpression Id. */
  int STRING_LITERAL = 73;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentarioSimples = 1;
  /** Lexical state. */
  int comentarioLongo = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "\"null\"",
    "\"import\"",
    "\"package\"",
    "\"class\"",
    "\"return\"",
    "\"System.out.println\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"static\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"final\"",
    "\"int\"",
    "\"boolean\"",
    "\"char\"",
    "\"String\"",
    "\"float\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\".*\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"public static void main\"",
  };

}
